import { buildDeskStructure } from './helpers';

const hiddenTypes = [
  'aiPage',
  'allCareersPage',
  'allclientspage',
  'allSmbClientsPage',
  'sidebarText',
  'allResourcesPage',
  'boardOfDirectorsPage',
  'bubbleCtaReference1',
  'cccPage',
  'checkBoxFormFieldReference',
  'clientEntity',
  'clientPage',
  'companyDescription',
  'countryFormFieldReference',
  'course',
  'customBackground',
  'dropdownFormFieldReference',
  'emailInputFormFieldReference',
  'event',
  'eventsPage',
  'executivePage',
  'filterCategory',
  'filterItem',
  'filterMenu',
  'filterDropdown',
  'footerMenu',
  'formBlurbReference',
  'formPage',
  'foundersPage',
  'gdprEmailFormFieldReference',
  'globalMenu',
  'glossaryPage',
  'glossaryTermPage',
  'grantEntity',
  'groupEntity',
  'gtmPage',
  'homepage',
  'industryEntity',
  'industrypage',
  'industryRecognitionPage',
  'marketplacePage',
  'marketplaceText',
  'menu',
  'newsBarSection',
  'newsCoverage',
  'newsCoveragesPage',
  'newsRoomPage',
  'officeAddressReference',
  'officeLocationsPage',
  'page',
  'partner',
  'partnerDetailPage',
  'partnerType',
  'partnerVertical',
  'person',
  'pressContact',
  'pressReleasePage',
  'partnerProductCategory',
  'productCategoryEntity',
  'productEntity',
  'productCategoryPage',
  'productPage',
  'redirect',
  'region',
  'route',
  'routePrefix',
  'resourceDetailPage',
  'resourceGalleryText',
  'quoteEntity',
  'searchpage',
  'sharedTilesReference',
  'shareWidget',
  'siteSettings',
  'smbPage',
  'smbProductPage',
  'socialMedia',
  'sortOption',
  'searchBar',
  'staticText',
  'subscriptionPage',
  'suitebenefitspage',
  'suitepage',
  'textAreaFormFieldReference',
  'textInputFormFieldReference',
  'thankYouPage',
  'userEntity',
];

const hiddenDocTypes = listItem => !hiddenTypes.includes(listItem.getId());

// build desk structure
const deskStructure = buildDeskStructure(hiddenDocTypes);

export default () => deskStructure;
